version: '3.8'

services:
  ams_backend:
    build:
      context: ./backend
      dockerfile: ../configs/php/Dockerfile
      args:
        - PHP_FPM_PORT=${PHP_FPM_PORT}
    container_name: ${BACKEND_CONTAINER_NAME}
    ports:
      - "${PHP_FPM_PORT}:${PHP_FPM_PORT}"
    volumes:
      - ./backend:/var/www/html
      - ./configs/php/php.ini:/usr/local/etc/php/conf.d/php.ini:ro
    depends_on:
      ams_db:
        condition: service_healthy
    networks:
      - ams_network
    environment:
      MONGO_URI: "mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@${DB_CONTAINER_NAME}:${MONGO_PORT}/${MONGO_DATABASE}?authSource=admin"
      MONGO_DB: ${MONGO_DATABASE}
      JWT_PASSPHRASE: ${JWT_PASSPHRASE}

  ams_web:
    image: nginx:alpine
    container_name: ${WEB_CONTAINER_NAME}
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
    volumes:
      - ./backend:/var/www/html
      - ./configs/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - ams_backend
    networks:
      - ams_network

  ams_db:
    image: mongo:latest
    container_name: ${DB_CONTAINER_NAME}
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    volumes:
      - mongodb_data:/data/db
    networks:
      - ams_network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

networks:
  ams_network:
    driver: bridge

volumes:
  mongodb_data:
